spring:
  application:
    name: pep-restaurant-ms-manager
  datasource:
    url: ${POSTGRES_DB_URL}/${PEP_RESTAURANT_MANAGER_DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.xml
server:
  port: 8082
  servlet:
      context-path: /pep/restaurant/manager
