spring:
  application:
    name: pep-restaurant-ms-manager
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432}/${PEP_RESTAURANT_MANAGER_DB:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:/db.changelog/changelog-master.xml
server:
  port: 8082
  servlet:
      context-path: /pep/restaurant/manager
