apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.serviceAccount.name }}
    labels:
        stage: {{ .Values.app.properties.environment }}
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: APP-26338
    annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::905418115951:role/eks-cluster-pep"
automountServiceAccountToken: false