name: Build

on:
    workflow_dispatch:
        inputs:
            to_promote:
                description: 'Promote'
                type: boolean
                required: false
                default: false
    push:
        branches:
            - master
            - feature/*
            - bugfix/*

jobs:
    Build:
        # Will push to ecr on manual trigger if "To Promote" box is checked, or on push if branch main.
        name: Build
        uses: porqueeuprogramo/pep-workflows/.github/workflows/wf_maven_micro_service.yml@main
        secrets: inherit
        with:
            ecr_repo: 'pep/pep-restaurant-ms-manager'
            to_promote: ${{ github.event_name == 'workflow_dispatch' && inputs.to_promote || github.ref == 'refs/heads/master' }}
